# Generated by scripts/update-releases. Do not edit release hashes by hand.
{
  stable = {
    version = "0.0.42";
    tag = "v0.0.42";
    srcHash = "sha256-YV86WqqpGQwjeovXB0IoE3f/o4IUC5DDVdBEdT4xzjc=";
    pnpmHash = "sha256-gEY2em9pNTC1EuVX0V3L/Wu1apZ+BKBXxALEcPQ/pwA=";
    cargoHash = "sha256-5cmG2daM1bVOA23gjjoalbx0fEL1hmqV6WZov0sUZp8=";
    npmHash = "sha256-dSWq1aevZsoFLDPxfKE/sw9R6zm1bbLj0gk/VpUH1yY=";
    pnpmVersion = "11.10.0";
    electronVersion = "44.1.0";
    client = {
      "aarch64-darwin" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.42/T3-Code-0.0.42-arm64.zip";
        hash = "sha256-BmOznpeQ8Hayp0uUReEXziu26CTQYZxXjoCLS6crRjc=";
      };
      "x86_64-linux" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.42/T3-Code-0.0.42-x86_64.AppImage";
        hash = "sha256-jcH8zavC7TpZo5RMx3LvEZMbk1FAHAlj7TBdX5bjzfQ=";
      };
    };
  };

  nightly = {
    version = "0.0.43-nightly.20260924.2223";
    tag = "v0.0.43-nightly.20260924.2223";
    srcHash = "sha256-yPfGCzt8z+5+IMRmSNDZQJtvn0GG5F/q2VT0sia4jhM=";
    pnpmHash = "sha256-RUJh4wO6bO37A+6IQ5axBCaZW7XSmzR7J4FgrasswRs=";
    cargoHash = "sha256-5cmG2daM1bVOA23gjjoalbx0fEL1hmqV6WZov0sUZp8=";
    npmHash = "sha256-gpAHkkuXOnVDmV4FyVHnXCik94ubfaNsQV7tQftJHBA=";
    pnpmVersion = "11.10.0";
    electronVersion = "44.4.2";
    client = {
      "aarch64-darwin" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.43-nightly.20260924.2223/T3-Code-0.0.43-nightly.20260924.2223-arm64.zip";
        hash = "sha256-JXNzbc3b2/0rxTy34VVbi3QWpnpAjBmda2gnHb7Glu8=";
      };
      "x86_64-linux" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.43-nightly.20260924.2223/T3-Code-0.0.43-nightly.20260924.2223-x86_64.AppImage";
        hash = "sha256-aQo3heHJGdrEI1C90tvuRrwHqfvJTfjyUVKvWkHjT+E=";
      };
    };
  };
}
