# Generated by scripts/update-releases. Do not edit release hashes by hand.
{
  stable = {
    version = "0.0.40";
    tag = "v0.0.40";
    srcHash = "sha256-J8kXpfMfm03/DDAiWXJuANwUNDshhiUn7Lf9tV42Xfw=";
    pnpmHash = "sha256-+UsoURSM4VP+CgF1fWROBEB85EuH+iJJM/xDPFigCKk=";
    cargoHash = "sha256-5cmG2daM1bVOA23gjjoalbx0fEL1hmqV6WZov0sUZp8=";
    npmHash = "sha256-M4AGI5pamFqbZliZGDUoeaP8Byfqci/puxoHRs7I6Gs=";
    pnpmVersion = "11.10.0";
    electronVersion = "43.4.1";
    client = {
      "aarch64-darwin" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.40/T3-Code-0.0.40-arm64.zip";
        hash = "sha256-v9kLAdoXayDLWG864pVlDCiuMhk3GV8gN2QIaNI0JgQ=";
      };
      "x86_64-linux" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.40/T3-Code-0.0.40-x86_64.AppImage";
        hash = "sha256-i/X9RMt/rQxDGR1U/v35dKgifVBQXsuKvPdjJiCfJko=";
      };
    };
  };

  nightly = {
    version = "0.0.41-nightly.20260911.1564";
    tag = "v0.0.41-nightly.20260911.1564";
    srcHash = "sha256-PiwePgpKG67LWm+kWt7G3fTQyR3s5ms6UwV70q4dVe8=";
    pnpmHash = "sha256-EO844JyOlqtUG+mGWOeXlVtQjRpFFgwiXRvTgfEh7ao=";
    cargoHash = "sha256-5cmG2daM1bVOA23gjjoalbx0fEL1hmqV6WZov0sUZp8=";
    npmHash = "sha256-EVjE4WZ7wi6Ll2ww4unD42V7XTtm8cxtei0Gy6f+MBA=";
    pnpmVersion = "11.10.0";
    electronVersion = "44.1.0";
    client = {
      "aarch64-darwin" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.41-nightly.20260911.1564/T3-Code-0.0.41-nightly.20260911.1564-arm64.zip";
        hash = "sha256-AxO6KWKWGwJmg9kJRWZxE4RHYoBF2v7Dod3MdgwZfvM=";
      };
      "x86_64-linux" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.41-nightly.20260911.1564/T3-Code-0.0.41-nightly.20260911.1564-x86_64.AppImage";
        hash = "sha256-37uUhrqB6BRf2nnivZ4UAHB3SHyWKiZgNB849U5qk10=";
      };
    };
  };
}
