# Generated by scripts/update-releases. Do not edit release hashes by hand.
{
  stable = {
    version = "0.0.38";
    tag = "v0.0.38";
    srcHash = "sha256-lbAOIlNwVxrjXA5jJGzmOm7Fe2ZcsnFuDzaSEt6R7G4=";
    pnpmHash = "sha256-t/hmpXdYPnBFx18A6NrSL4zSvVnUDIjIPtLjGOzoaDk=";
    cargoHash = "sha256-5cmG2daM1bVOA23gjjoalbx0fEL1hmqV6WZov0sUZp8=";
    npmHash = "sha256-OnsZvRvP6RVif9oyhpm+LuQvM4PSn472n7tpdsWwe40=";
    pnpmVersion = "11.10.0";
    electronVersion = "43.4.1";
    client = {
      "aarch64-darwin" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.38/T3-Code-0.0.38-arm64.zip";
        hash = "sha256-wKde9820O8ubcgiVwSVuG1BRs5jFwX+Jp4xTOE5KQz4=";
      };
      "x86_64-linux" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.38/T3-Code-0.0.38-x86_64.AppImage";
        hash = "sha256-HxzNkisu+v/VBEewKO4NbiUlUCkFCHz4rj/kHv6+NG8=";
      };
    };
  };

  nightly = {
    version = "0.0.39-nightly.20260905.1284";
    tag = "v0.0.39-nightly.20260905.1284";
    srcHash = "sha256-P+LHtHhBNNB2+Jf+SeKuMpwA9F/ono/g46Q5lZATJyE=";
    pnpmHash = "sha256-mgRMeBpJmiTat38APyE4guNJ+6RiQhenphP7tRcmc+k=";
    cargoHash = "sha256-5cmG2daM1bVOA23gjjoalbx0fEL1hmqV6WZov0sUZp8=";
    npmHash = "sha256-85dD2zGrId+MULWBplus9kx0KPjSeGuNeWNN0b568hY=";
    pnpmVersion = "11.10.0";
    electronVersion = "43.4.1";
    client = {
      "aarch64-darwin" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.39-nightly.20260905.1284/T3-Code-0.0.39-nightly.20260905.1284-arm64.zip";
        hash = "sha256-aZO+/3jMhqBM4dxNDgyH4KeYSu+znj+cZN+or41kyBU=";
      };
      "x86_64-linux" = {
        url = "https://github.com/pingdotgg/t3code/releases/download/v0.0.39-nightly.20260905.1284/T3-Code-0.0.39-nightly.20260905.1284-x86_64.AppImage";
        hash = "sha256-BqKsZlqaSvlo3JmcK5qhDU1yDGsVb9iDy/FEsro1r04=";
      };
    };
  };
}
